import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Blog from "@/components/blog";
import SideNav from "@/components/sidenav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "REMWaste App",
  description: "Generated by REMWaste",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="text-primary">
          <div className="fixed -z-[1] left-1/3 w-12 top-2/3 blur-2xl">
            <Blog blur/>
          </div>
          
          <div className="fixed -z-[1] left-2/3 w-12 top-2/3 blur-2xl">
            <Blog blur/>
          </div>

          <div className="fixed -z-[1] left-1/4 w-40 top-1/4 blur-2xl opacity-50">
            <Blog blur />
          </div>

          <div className="fixed -z-[1] left-1/2 w-32 top-1/2 blur-2xl opacity-60">
            <Blog blur />
          </div>

          <div className="fixed -z-[1] left-[45%] w-12 top-1/3 blur-2xl ">
            <Blog blur />
          </div>

          <div className="fixed -z-[1] left-3/4 w-60 top-1/3 blur-2xl opacity-20">
            <Blog blur />
          </div>
        </div>
        <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
          <div className="w-full flex-none md:w-64">
            <SideNav/>
          </div>
          <div className="flex-grow p-6 md:overflow-y-auto md:p-12">{children}</div>
        </div>
        
      </body>
    </html>
  );
}
